### ISSUE TITLE
Images end of life?

### ISSUE THREAD

**Issue by tabdulradi** [tianon/docker-brew-ubuntu-core#101]
Sorry if this is the wrong place to ask. 

Does the docker images follow the same end-of-life date as their respective Ubuntu versions?
I am using "ubuntu:14.04" image, is it going to be supported till early 2019 as per [ubuntu's website](https://www.ubuntu.com/info/release-end-of-life)?

**Comment by graingert** [comment]
As long as Ubuntu keep shipping partner images, then most likely. Have you
tried upgrading to a newer LTS?

**Comment by tabdulradi** [comment]
Yes, I am planning to upgrade soon, just wanted to know my limits :) 
Thanks a lot for the quick answer.

**Comment by tianon** [comment]
Yes, these images will include 14.04 as long as Canonical still supports it and still builds Docker tarballs for it.
