### ISSUE TITLE
rolling -> artful and 20171019

### ISSUE THREAD

**Issue by graingert** [tianon/docker-brew-ubuntu-core#103]
@tianon good news, rolling was updated super early today!

**Comment by graingert** [comment]
@tianon can you sync with the latest partner images plzzz :heart: ?

**Comment by tianon** [comment]
Yep!  I kicked off that build job as soon as I merged this PR, and will
make the official-images PR a little later today. 👍

**Comment by graingert** [comment]
super hyped for the new release!

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/3601 :+1:
