### ISSUE TITLE
i386 Yakkety container

### ISSUE THREAD

**Issue by jbglaw** [tianon/docker-brew-ubuntu-core#112]
Hi!

Right now, there is not Yakkety Yak i386 Docker available. Looking at the scripts, this wouldn't be all that hard to prepare. Would be nice to have one!

Thanks a lot,
  Jan-Benedict

**Comment by yosifkit** [comment]
Yakkety Yak is eol as of 20 July 2017 so it will not receive any new images or updates. (https://fridge.ubuntu.com/2017/07/20/ubuntu-16-10-yakkety-yak-end-of-life-reached-on-july-20-2017/)  But we do not delete old images and it is still available:

```console
$ docker pull i386/ubuntu:yakkety
yakkety: Pulling from i386/ubuntu
0b754db5c925: Pull complete 
f72ea698a499: Pull complete 
26e7b6cabe92: Pull complete 
a56e0244aaff: Pull complete 
034082ae54b7: Pull complete 
Digest: sha256:42608392a2e500eaae8a2d1fd244b7fe35a0d2278b85311417525a9dfbd02104
Status: Downloaded newer image for i386/ubuntu:yakkety
```
