### ISSUE TITLE
docker image ubuntu:16.04 linux kernel mismatch

### ISSUE THREAD

**Issue by hougangliu** [tianon/docker-brew-ubuntu-core#113]
# docker run -ti ubuntu:16.10 cat /proc/version
Linux version 3.10.0-693.el7.x86_64 (mockbuild@x86-038.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) ) #1 SMP Thu Jul 6 19:56:57 EDT 2017

hower , as ubuntu releasenotes says "Ubuntu 16.04 LTS is based on the long-term supported Linux release series 4.4. " refer to https://wiki.ubuntu.com/XenialXerus/ReleaseNotes

**Comment by benileo** [comment]
"There's no kernel inside a container. Even if you install a kernel, it won't be loaded when the container starts. The very purpose of a container is to isolate processes without the need to run a new kernel."
