### ISSUE TITLE
xenial-20180123 not found

### ISSUE THREAD

**Issue by austinnichols101** [tianon/docker-brew-ubuntu-core#117]
On https://hub.docker.com/_/ubuntu/ the latest links show as follows:

Supported tags and respective Dockerfile links
17.10, artful-20180123, artful, rolling (artful/Dockerfile)
18.04, bionic-20180125, bionic, devel (bionic/Dockerfile)
14.04, trusty-20180123, trusty (trusty/Dockerfile)
16.04, xenial-20180123, xenial, latest (xenial/Dockerfile)

However, the `xx-20180123` are not shown under the `tags` tab and a docker pull of the image fails.  Based on `tags`, the latest appears to be `trusty-20180112`.

```
docker pull ubuntu:xenial-20180123
Error response from daemon: manifest for ubuntu:xenial-20180123 not found
```

**Comment by tianon** [comment]
The build/push is currently in progress -- see https://github.com/docker-library/official-images/pull/3934 for where this update was officially merged only ~1hr ago.
