### ISSUE TITLE
32-bit images

### ISSUE THREAD

**Issue by liori** [tianon/docker-brew-ubuntu-core#12]
Hello,

I've just tried replacing `amd64` with `i386` in the `update.sh` script, run `update.sh trusty` and got a perfectly fine 32-bit image. Would it be possible for you to also maintain 32-bit images this way? My use case is running wine inside, which seems to be quite a bit easier for me on i386.

Thanks,

**Comment by tianon** [comment]
These are available at https://hub.docker.com/r/i386/ubuntu/ now! :+1:
