### ISSUE TITLE
Provide nano or vi in ubuntu:xenial

### ISSUE THREAD

**Issue by krichter722** [tianon/docker-brew-ubuntu-core#121]
`ubuntu:xenial` neither has `nano`, `pico` nor `vi` or `vim` which are popular editors and at least one of them should be provided.

**Comment by graingert** [comment]
This docker image just pulls the official Ubuntu cloud images. If you want to have a package added you should ask on their issue tracker

**Comment by yosifkit** [comment]
@graingert is correct

See also https://github.com/debuerreotype/docker-debian-artifacts/issues/38#issuecomment-388181457.
