### ISSUE TITLE
Creating docker image fails 

### ISSUE THREAD

**Issue by prabhavs** [tianon/docker-brew-ubuntu-core#127]
I am creating a docker image from ubuntu:18.04. It worked very well until yesterday. Today I am facing the package validity issue. 

Here is the error:

Sending build context to Docker daemon  89.67MB
Step 1/16 : FROM ubuntu:18.04
 ---> 113a43faa138
Step 2/16 : MAINTAINER Prabha Vadlamani prabha@novaiq.io
 ---> Using cache
 ---> 940800681286
Step 3/16 : RUN apt-get update && apt-get install -y --no-install-recommends apt-utils
 ---> Running in 8952c9999130
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [83.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic/universe Sources [11.5 MB]
Get:6 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Get:7 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:8 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Reading package lists...
E: Release file for http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease is not valid yet (invalid for another 2d 11h 51min 25s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 2d 11h 51min 28s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease is not valid yet (invalid for another 2d 11h 51min 44s). Updates for this repository will not be applied.
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends apt-utils' returned a non-zero code: 100

**Comment by tianon** [comment]
Looks like your system clock is off -- did you suspend/resume recently?  Do you use NTP or something similar for synchronizing your host clock?

Either way, this is either an issue in your local system or in the released artifacts on the official Ubuntu servers -- not something particular to the image (so I'm going to close).

**Comment by prabhavs** [comment]
Thank you for the quick response. However, my clock was not off and I do not use any synchronizing for the same. 

It gave me a different error today. It must be an issue with Ubuntu severs only. What would be the work around for such a dependency on artifacts on which we do not have control? Archive the docker image when it works and use it? Can we have the stabilization built into the image building?
