### ISSUE TITLE
Ubuntu Minimal

### ISSUE THREAD

**Issue by JBodkin-LH** [tianon/docker-brew-ubuntu-core#129]
Canonical have recently introduced minimal images that are suitable for containers that weight in at 29MB. See blog post: https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released

Would it be possible to have differently tagged containers built from these images?

**Comment by JBodkin-LH** [comment]
Yes, it does appear that they are talking about the compressed size. Just reading the blog post again and I also believe these images are already being used. "This is the standard Ubuntu 18.04 LTS image on the Docker Hub."

**Comment by mwhudson** [comment]
Whoops yes, sorry for not replying, the docker images are essentially the
same image. The difference to the announced images for EC2 etc is that the
latter of course have kernels in, and getting that end of things working
(e.g. booting without an initramfs) is where the recent work has been going.
