### ISSUE TITLE
Ubuntu 18.04 image has python (2.7) installed by default

### ISSUE THREAD

**Issue by notacollins** [tianon/docker-brew-ubuntu-core#131]
Neither the ubuntu:xenial docker image nor the native ubuntu 18.04 install have python installed by default, from my understanding. This may cause problems when dealing with scripts that have python shebang'd, as those scripts may get an undesirable version of python.

**Comment by mwhudson** [comment]
I don't understand. As far as I can tell no official docker image since 12.04 has had python by default. If you want it, install it :)

**Comment by notacollins** [comment]
Ah, looks like I had a package installing it as a dependency, which caused some confusion on my part. Thanks for answering!
