### ISSUE TITLE
deb-src entries missing in /etc/apt/sources.list

### ISSUE THREAD

**Issue by rnestler** [tianon/docker-brew-ubuntu-core#138]
According to https://hub.docker.com/r/_/ubuntu/ the docker image should contain the deb-src entries in the /etc/apt/sources.list file:

> $ docker run ubuntu:16.04 grep -v '^#' /etc/apt/sources.list
>
>deb http://archive.ubuntu.com/ubuntu/ xenial main restricted
>deb-src http://archive.ubuntu.com/ubuntu/ xenial main restricted
>
>deb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted
>deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted
>
>deb http://archive.ubuntu.com/ubuntu/ xenial universe
>deb-src http://archive.ubuntu.com/ubuntu/ xenial universe
>deb http://archive.ubuntu.com/ubuntu/ xenial-updates universe
>deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates universe
>
>deb http://archive.ubuntu.com/ubuntu/ xenial-security main restricted
>deb-src http://archive.ubuntu.com/ubuntu/ xenial-security main restricted
>deb http://archive.ubuntu.com/ubuntu/ xenial-security universe
>deb-src http://archive.ubuntu.com/ubuntu/ xenial-security universe

But this isn't the case anymore:
```
% docker run ubuntu:16.04 grep -v '^#' /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu/ xenial main restricted

deb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted

deb http://archive.ubuntu.com/ubuntu/ xenial universe
deb http://archive.ubuntu.com/ubuntu/ xenial-updates universe

deb http://archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse

deb http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted
deb http://security.ubuntu.com/ubuntu/ xenial-security universe
deb http://security.ubuntu.com/ubuntu/ xenial-security multiverse
```

This leads to the following error in one of my dependent Dockerfile:

`E: You must put some 'source' URIs in your sources.list`

This used to work with older versions of the 16.04 image.

**Comment by thenewguy** [comment]
Same in 14.04

**Comment by tianon** [comment]
The `sources.list` content in this image comes directly from the tarballs that Canonical publishes (https://partner-images.canonical.com/core/), so if they're not what you'd expect, you should file an issue on their cloud-images bug tracker as noted on https://hub.docker.com/_/ubuntu.

**Comment by tianon** [comment]
Good point, I think it's probably appropriate to just remove that section now.  I'll make a PR to do that shortly.
