### ISSUE TITLE
Repoint rolling at disco

### ISSUE THREAD

**Issue by alex** [tianon/docker-brew-ubuntu-core#143]
rolling points at cosic ATM.

I think this is just a matter of editing https://github.com/tianon/docker-brew-ubuntu-core/blob/master/rolling but the CONTRIBUTING.md suggested I shouldn't send a PR.

**Comment by tianon** [comment]
Good catch, thanks!  For future reference, this is one of those things that a PR would be great for -- we probably need to adjust `CONTRIBUTING.md` to be more clear that it's the `dist-*` branches we don't want PRs for. :sweat_smile:
