### ISSUE TITLE
Ubuntu trusty availability

### ISSUE THREAD

**Issue by zerkms** [tianon/docker-brew-ubuntu-core#145]
Given that ubuntu 14.04 reaches its EOL tomorrow (April 30th, 2019) will the trusty image be available for at least some time or is it better to re-upload it to personal docker hub repositories?

Asking on behalf of those poor people who still has not upgraded for one or another reason.

**Comment by mwhudson** [comment]
Images for older releases are not removed, you can still find images for e.g. precise or raring and there are no plans to remove the trusty images either.

**Comment by zerkms** [comment]
Thanks a bunch for a quick response, and yep - I should have checked myself first for the older releases tags, sorry.
