### ISSUE TITLE
Release Ubuntu 18.04.3 LTS ?

### ISSUE THREAD

**Issue by labianchin** [tianon/docker-brew-ubuntu-core#155]
Hi, according to https://lists.ubuntu.com/archives/ubuntu-announce/2019-August/000248.html and https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes, there is now a new Ubuntu Bionic version (Ubuntu 18.04.3 LTS).

Can we have a new release of the `ubuntu:bionic-20190807` docker repository ? https://partner-images.canonical.com/core/bionic/20190807/

If I understood the readme, I think I am asking to:

> 2. The button is clicked by someone with appropriate permissions to run https://doi-janky.infosiftr.net/job/tianon/job/update-ubuntu/ (this job is defined by https://github.com/docker-library/oi-janky-groovy/blob/master/tianon/update-ubuntu-pipeline.groovy)

Let me know if I can help with anything.

PTAL @tianon

**Comment by tianon** [comment]
Great point, doing that now! :+1: :heart:

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/6462 :+1:
