### ISSUE TITLE
ubuntu:19.04 image seems to have a bad /bin folder

### ISSUE THREAD

**Issue by dreamcat4** [tianon/docker-brew-ubuntu-core#156]
Hi there,
When I was changing my docker base image today `FROM ubuntu:18.04`  to `ubuntu:19.04`, I noticed that my image was no longer building correctly anymore. And the reason was because the underlying base image filesystem was very different.

So I do some investigating and this leads me to the current archive file uploaded in `disco/ubuntu-disco-core-cloudimg-amd64-root.tar.gz`

https://github.com/tianon/docker-brew-ubuntu-core/blob/9db8c72dd02e8f9fd5dba82ff9266174b088e2e6/disco/ubuntu-disco-core-cloudimg-amd64-root.tar.gz

Which is currently 7 days old now. And currently tagged in docker hub as:

`19.04, disco-20190809, disco, rolling`

Noticed 2 simple things, strange (different) in this archive:

1) The folder `/bin` is not a real folder. Instead it has been moved to the location `/usr/bin` and a symlink placed instead from `/bin` pointing to `/usr/bin`.

I am not sure whether or not this has been a deliberate action. Or if so, then what has actually happened to whatever the prior contents of the previous `/usr/bin` folder. If it was either overwritten by the new location of the moved `/bin`. And therefore got obliterated, or if it was instead more safely merged both folders together into a single new folder.

It is curious to me because I happen to be running a regular `19.04` desktop system over here. Upgraded from earlier ubuntu version(s). And it has a real `/bin/` folder. And so I am not certain what the intention is.

2) Inside of the `/bin/` ahem now `/usr/bin` folder. There is an executable file named `[`. Well this does seem to be a real scripting mistake occuring somewhere. Since I know of no unix program named `[`.

I am not sure if 2) is related to 1) in any way. Perhaps yes or perhaps no.

However here is my own issue with this new image:

Whenever i need to unpack an archive ontop of this new base image, like this:

```sh
RUN tar zxf /tmp/s6-overlay-amd64.tar.gz -C /
```

Then the `tar` program will, in the process of adding any new files to the folder `/bin` then actually overwrite that `/bin/` symlink entirely. And `tar` will instead replace the symlink file with a brand new real folder named `/bin`. And then populate that new folder with the contents of the tar archive it is unpacking. Which then unlinks and breaks anything that was in the contents of `/bin` symlink. Which of course also includes the `sh` interpreter. Which in turn is breaking the entire docker build. Since the program `/bin/sh` is now missing from that location. But still required for docker's `RUN` command to operate successfully.

This breaks all of my existing docker builds. Due to the way that the program `tar` operates when it encounters a symlink, and instead overwrites it with a real folder.

Hopefully this makes the nature of this issue clear. Anybody can download and inspect the contents of the rootfs archive from your repo here:

https://github.com/tianon/docker-brew-ubuntu-core/blob/9db8c72dd02e8f9fd5dba82ff9266174b088e2e6/disco/ubuntu-disco-core-cloudimg-amd64-root.tar.gz

And will come to the same conclusion about these differences in the filesystem structure. Which has diverged from what was previously in the `ubuntu:18.04` official base image.

Not sure why nobody else has noticed this problem yet. Since `19.04` docker images have been available for quite some time now. However maybe it's genuinely some recent bug that was introduced only in the latest image versions? I.e. are there previous `19.04` (`disco`) images that were not like this? Or it was always the case with all, even the earliest `19.04` image ?

It would be very much appreciated, if this matter can be looked into any further. Many thanks.

**Comment by dreamcat4** [comment]
Unfortunately @tianon when i look at the git commit history here, I cannot see myself that the git history goes back back very far. To help answer the question of when this change first happen. Perhaps it is because you are forcing your pushes? To stop the repository size from growing too big / out of control? I assume that is the reason.

Can simply see its not occur in the prior `18.10` cosmic images. Then (as previously discussed), it first began somewhere in `19.04`, and it also occur in the newer devel / `19.10` eoan branch too. Which i didn't mention before.

**Comment by mwhudson** [comment]
> 1. The folder `/bin` is not a real folder. Instead it has been moved to the location `/usr/bin` and a symlink placed instead from `/bin` pointing to `/usr/bin`.

This is the so-called "usrmerge" change that has been happening across the linux landscape for a while now: https://www.freedesktop.org/wiki/Software/systemd/TheCaseForTheUsrMerge/

Existing installs are not merged on upgrade which explains why your install is different.

> 1. Inside of the `/bin/` ahem now `/usr/bin` folder. There is an executable file named `[`. Well this does seem to be a real scripting mistake occuring somewhere. Since I know of no unix program named `[`.

In this case, the only reason you might not know of this program is because you haven't looked <wink>. It'll be there on your other install too (it's part of coreutils, which is an Essential package)

I don't know why tar is misbehaving for you. There is probably some command line flag you can pass to make it do what you want? But these are not bugs in the image, so closing.

**Comment by dreamcat4** [comment]
OK thanks for enlightening me about this... I am very grateful. And have been able to come up with a workaround for my images now.

**Comment by soullivaneuh** [comment]
Does a fix is coming for that? Or a workaround guide?

I have the following rootfs I usually add to build my alpine/debian/ubuntu variants:

```
❯ ls -lR rootfs
rootfs:
total 8
drwxr-xr-x 2 sullivan sullivan 4096 10 oct.  12:14 bin
drwxr-xr-x 2 sullivan sullivan 4096 10 oct.  11:40 etc

rootfs/bin:
total 8
-rwxr-xr-x 1 sullivan sullivan 267 10 oct.  12:14 bin-install
-rwxr-xr-x 1 sullivan sullivan 162 10 oct.  12:14 setup

rootfs/etc:
total 12
-rw-r--r-- 1 sullivan sullivan  35  8 oct.  11:31 bash.bashrc
-rw-r--r-- 1 sullivan sullivan 218  8 oct.  11:31 motd
-rw-r--r-- 1 sullivan sullivan  15 10 oct.  11:40 packages
```

This works well with `COPY rootfs /` except for this case because of the symbolic link.

**Comment by soullivaneuh** [comment]
I found this workaround (line 2):

```
FROM ubuntu:${UBUNTU_TAG} as ubuntu
# @see https://github.com/tianon/docker-brew-ubuntu-core/issues/156
RUN test ! -L /bin || (rm /bin && mkdir /bin && ln -s /usr/bin/* /bin/)
COPY --from=core / /
RUN apt-get update \
  && apt-get install --yes $(cat /etc/packages) \
  && rm --recursive --force /var/lib/apt/lists/*
RUN setup
```

**Comment by tianon** [comment]
I don't think there's a fix coming because it's not considered a bug.
