### ISSUE TITLE
Getting error in building dockerfile

### ISSUE THREAD

**Issue by gauravahlawat81** [tianon/docker-brew-ubuntu-core#174]
I am trying to build this image using your dockerfile, I copied the content of the dockerfile, ran docker build .
But I am getting error like
```
ADD failed: stat /var/lib/docker/tmp/docker-builder892477703/ubuntu-bionic-core-cloudimg-amd64-root.tar.gz: no such file or directory
```
Can you tell me the way around ?
I have downloaded the tar file in the same directory as docker file.

**Comment by tianon** [comment]
If you want to build locally, I'd suggest either using the official `update.sh` script or one of the `dist-*` branches.
