### ISSUE TITLE
General question on package update

### ISSUE THREAD

**Issue by fd98279** [tianon/docker-brew-ubuntu-core#188]
Hi All,

What is the recommend approach to update packages due to security recommendation? Certain packages are being recommended to be upgraded to next minor version due to security fixes.

Should that be done in our environments locally or canonical can update the base image?

Thanks,
Sampat

**Comment by yosifkit** [comment]
> We strive to publish updated images at least monthly for Debian and Ubuntu. We also rebuild earlier if there is a critical security need, e.g. docker-library/official-images#2171.
>
> \-https://github.com/docker-library/faq/#why-does-my-security-scanner-show-that-an-image-has-cves

So the Ubuntu and Debian images (and all their dependent images in Official-Images) are rebuilt fairly often, if your organization has different security needs then you'll need to address it at your level.
