### ISSUE TITLE
Bash Security Vulnerability 

### ISSUE THREAD

**Issue by ashirvadgupta** [tianon/docker-brew-ubuntu-core#189]
Hi Team,

In 18.04, what is the plan on fixing bash vulnerabilities?

**Comment by tianon** [comment]
I just scanned the latest `ubuntu:18.04` (digest `sha256:646942475da61b4ce9cc5b3fadb42642ea90e5d0de46111458e100ff2c7031e6`) with Clair, and there don't appear to be any fixable vulnerabilities in that image -- is there a particular vulnerability you're interested in?

See also https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by mwhudson** [comment]
We rebuild the images roughly every month and that picks up any security updates that have been made in the distro. We accelerate this for particularly bad bugs.

Did you have any particular vulnerability in ming

**Comment by tianon** [comment]
Images have been rebuilt several times since this was opened - if there's an additional vulnerability here that isn't fixed, I'd suggest contacting Canonical's security team privately (so it can be responsibly disclosed and hopefully fixed).
