### ISSUE TITLE
Should LANG=C.UTF-8 be the default?

### ISSUE THREAD

**Issue by NobodysNightmare** [tianon/docker-brew-ubuntu-core#190]
Hello,

today I stumbled upon the fact that I wasn't able to type Unicode letters in the terminal and that existing unicode letters were not displayed correctly.

I found [this StackOverflow answer](https://stackoverflow.com/a/27102762/968531) as well as #25, which both point me into the same direction: Setting `LANG=C.UTF-8` will fix the issue.

Since none of the two places discussed this so far, I want to raise the question why Unicode support is not the default. Are there backwards-compatibility issues with having `LANG=C.UTF-8` set as an overwritable default?

Or is this not an issue with the docker images provided here, but rather with Ubuntu itself?

**Comment by tianon** [comment]
This repository is no longer canonical; see https://github.com/tianon/docker-brew-ubuntu-core/pull/248 for more details.
