### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by rleinfellner** [tianon/docker-brew-ubuntu-core#192]
[+] Building 0.1s (4/7)
 => [internal] load build definition from Dockerfile                                                                                                                                         0.0s
 => => transferring dockerfile: 32B                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                                              0.0s
 => [internal] load build context                                                                                                                                                            0.0s
 => => transferring context: 2B                                                                                                                                                              0.0s
 => ERROR [1/4] ADD ubuntu-bionic-core-cloudimg-amd64-root.tar.gz /                                                                                                                          0.0s
------
 > [1/4] ADD ubuntu-bionic-core-cloudimg-amd64-root.tar.gz /:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to compute cache key: "/ubuntu-bionic-core-cloudimg-amd64-root.tar.gz" not found: not found

**Comment by tianon** [comment]
If you want to build from source, you'll either need to fetch the appropriate tarballs from Canonical yourself, or build from one of the architecture-specific `dist-*` branches which includes the appropriate tarballs.

For example: `docker build https://github.com/tianon/docker-brew-ubuntu-core.git#dist-amd64:bionic`

**Comment by normatov11** [comment]
gghgu
