### ISSUE TITLE
Can't change default shell on ubuntu:focal

### ISSUE THREAD

**Issue by abelfodil** [tianon/docker-brew-ubuntu-core#200]
I can't change the default shell through `chsh` or `usermod` utilities. Each time after running one of the commands, the `/etc/passwd` is cleared.

Steps to Reproduce:

1. ` docker run -it ubuntu /bin/bash`
2. `apt update && apt install -y fish`
3. `cat /etc/passwd` (file is not empty)
4. `chsh -s $(which fish)` (get error chsh: user 'root' does not exist in /etc/passwd)
5. `cat /etc/passwd` (file is empty)

**Comment by abelfodil** [comment]
I have no issues with `bionic`.

**Comment by tianon** [comment]
I can't reproduce any issue with focal and `chsh`: :confused:

```console
$ docker pull ubuntu:focal
focal: Pulling from library/ubuntu
Digest: sha256:c95a8e48bf88e9849f3e0f723d9f49fa12c5a00cfc6e60d2bc99d87555295e4c
Status: Image is up to date for ubuntu:focal
docker.io/library/ubuntu:focal
$ docker run -it --rm ubuntu:focal
root@d700c0a86cbd:/# grep ^root /etc/passwd
root:x:0:0:root:/root:/bin/bash
root@d700c0a86cbd:/# chsh --shell /bin/sh
root@d700c0a86cbd:/# grep ^root /etc/passwd
root:x:0:0:root:/root:/bin/sh
```

**Comment by abelfodil** [comment]
I tried on another machine and I can't reproduce the issue :O

I tried `docker system prune --all --volumes` on the faulty machine and I still get the same error. Do you have an idea what could cause the issue?
