### ISSUE TITLE
Writing more data than expected 

### ISSUE THREAD

**Issue by ricky001** [tianon/docker-brew-ubuntu-core#203]
while updating the ubuntu16 32 bit docker image using apt-get update it gives below error

E: Failed to fetch http://mirror.enzu.com/ubuntu/pool/main/g/gcc-5/libgcc-5-dev_5.4.0-6ubuntu1~16.04.12_i386.deb  Writing more data than expected (8241631 > 8230232)

E: Failed to fetch http://mirror.enzu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.4.0-203.235_i386.deb  Writing more data than expected (8239419 > 8230232)

E: Failed to fetch http://mirror.enzu.com/ubuntu/pool/main/g/glibc/libc6-dev_2.23-0ubuntu11.2_i386.deb  Writing more data than expected (8233763 > 8230232)

E: Failed to fetch http://mirror.enzu.com/ubuntu/pool/main/g/gcc-5/libstdc++-5-dev_5.4.0-6ubuntu1~16.04.12_i386.deb  Writing more data than expected (8251167 > 8230232)

E: Failed to fetch http://mirror.enzu.com/ubuntu/pool/main/libx/libx11/libx11-doc_1.6.3-1ubuntu2.2_all.deb  Writing more data than expected (8238347 > 8230232)

E: Failed to fetch http://mirror.enzu.com/ubuntu/pool/main/m/manpages/manpages-dev_4.04-2_all.deb  Writing more data than expected (8283612 > 8230232)

E: Failed to fetch http://mirror.enzu.com/ubuntu/pool/main/o/openjdk-8/openjdk-8-jdk-headless_8u282-b08-0ubuntu1~16.04_i386.deb  Writing more data than expected (8234660 > 8230232)

**Comment by yosifkit** [comment]
That usually means a temporary mirror issue or an outdated local apt cache. Be sure to do `apt-get update` in the same `RUN` line that is installing the packages.
