### ISSUE TITLE
less command missing Ubuntu 20.10 image

### ISSUE THREAD

**Issue by aplatypus** [tianon/docker-brew-ubuntu-core#209]
I am just starting with containers and thought I'd begin with Ubuntu as Im familar with it already.  I am running a `bash` session interactively, as follows:

     podman --runtime=crun  run --rm --interactive --userns=keep-id --tty   ubuntu:20.10 bash

The Image Id is: 69040ea16df0

I attempted to use the `less` command -- It was not found.  the `more` command is there.  I don't know if this is an oversight or not. 

I would expect the basic commands to be present.

**Comment by tianon** [comment]
This is expected -- the images only contain the bare minimum necessary.  If you need `less`, you'll need to install it:

```dockerfile
FROM ubuntu:20.10
RUN apt-get update && apt-get install -y less
```
