### ISSUE TITLE
how to tell the version of python3 supported in the default repository without installing?

### ISSUE THREAD

**Issue by simkimsia** [tianon/docker-brew-ubuntu-core#211]
I'm using `ubuntu:focal-20210609`

and I instsall python3 using the default repository

```
# for other standard libraries
RUN apt-get install -y --no-install-recommends \
    # psycopg2 dependencies
    libpq-dev gcc python3-dev  \
```

My question is how do I tell the version of the default python3 without actually installing and then running `python3 -V`?

**Comment by tianon** [comment]
I think https://packages.ubuntu.com/focal/python3 is the easy answer, but `apt-cache` is useful if you want a command-line way to get information like that from the container/image itself.

**Comment by tianon** [comment]
(For further help, I'd suggest a dedicated support forum such as those listed on https://ubuntu.com/support/community-support)
