### ISSUE TITLE
changelogs of "native" packages are missing

### ISSUE THREAD

**Issue by henning-schild** [tianon/docker-brew-ubuntu-core#216]
`/etc/dpkg/dpkg.cfg.d/excludes` is only allowing `/usr/share/doc/*/changelog.Debian.*` but not `/usr/share/doc/*/changelog.*`

The result is that even the Debian changelog will be missing for "native" packages.

http://manpages.ubuntu.com/manpages/impish/en/man1/dh_installchangelogs.1.html

>           The changelog file is installed with a name of changelog for native packages, and
>           changelog.Debian for non-native packages.  The NEWS file is always installed with a
>           name of NEWS.Debian.

I think the `excludes` file should instead use `/usr/share/doc/*/changelog.*` to include Debian changelogs no matter what kind of package "native" vs. "non-native". Doing that would also not exclude upstream changelogs, which might grow that image but probably be just as valid as keeping the Debian changelog.

I hope this is the right place, did not find the code responsible and that exclude is already in the images coming from https://partner-images.canonical.com/core/

**Comment by tianon** [comment]
I think your chances of reaching the folks who maintain the tarballs are higher if you file an issue on https://bugs.launchpad.net/cloud-images (including the `docker` tag).

**Comment by henning-schild** [comment]
https://bugs.launchpad.net/cloud-images/+bug/1943114

**Comment by tianon** [comment]
Perfect, closing in favor of that :+1:
