### ISSUE TITLE
Cannot create new threads in Ubuntu 21.10

### ISSUE THREAD

**Issue by feikesteenbergen** [tianon/docker-brew-ubuntu-core#217]
While preparing some Docker Images to depend on Ubuntu 21.10 I run into multiple awkward issues, for example:

`apt-get update`
```
Hit:1 http://archive.ubuntu.com/ubuntu impish InRelease
Hit:2 http://archive.ubuntu.com/ubuntu impish-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu impish-backports InRelease          
Hit:4 http://security.ubuntu.com/ubuntu impish-security InRelease          
Reading package lists... Done
E: Problem executing scripts APT::Update::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
```

Stracing shows the following:
```
888   clone3(0x7ffe883ceeb0, 88)        = -1 EPERM (Operation not permitted)
```

Or, when trying to install rust, using `rust-init`:
`./rustup-init -y --no-modify-path --profile minimal --default-toolchain 1.54.0 --default-host x86_64-unknown-linux-gnu`
```
[...]
#24 0.840 info: setting default host triple to x86_64-unknown-linux-gnu
#24 0.842 info: syncing channel updates for '1.54.0-x86_64-unknown-linux-gnu'
#24 0.842 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Builder, source: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" } }', download/src/lib.rs:339:23
```

When stracing the `rustup-init` call I could see the following:
```
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7f6f3db16910, parent_tid=0x7f6f3db16910, exit_signal=0, stack=0x7f6f3d916000, stack_size=0x1ffb80, tls=0x7f6f3db16640}, 88) = -1 EPERM (Operation not permitted)
```

As clone3 has to do with processes/threads, I thought to try to create a thread in python:
*test.py*
```python
#!/usr/bin/env python3
from threading import Thread

def sleep():
  pass

thread = Thread(target = sleep)
thread.start()
```

Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/threading.py", line 892, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

> On Ubuntu 21.04 the above works without any errors

To reproduce:

*Dockerfile*
```
FROM ubuntu:21.10

RUN apt-get update
RUN apt-get install -y lsb-release
```

*console
```
python3 ./example.py
```

Currently using a Docker Image Ubuntu 21.10: `docker.io/library/ubuntu:21.10@sha256:5780eeea246d5e8e76c20dfedf03d4d9568cd4ba00af5a7e3762b6976df2b631`

**Comment by feikesteenbergen** [comment]
Seems https://giters.com/moby/moby/issues/42680?amp=1 might provide some insights as well.

**Comment by tianon** [comment]
Thanks for the report!  I'm going to close this in favor of https://bugs.launchpad.net/cloud-images/+bug/1943049 which has more detail (and frankly more stakeholders involved who might be able to resolve it in a reasonable way). :smile:
