### ISSUE TITLE
Ubuntu:20.04 image usage guidelines

### ISSUE THREAD

**Issue by bharanitharanm** [tianon/docker-brew-ubuntu-core#223]
We are planning yo adopt ubuntu base docker image [ubuntu:20.04](https://hub.docker.com/layers/ubuntu/library/ubuntu/20.04/images/sha256-97d755cb1cbe1dc714fb21771ac50e517a48125d8fd9f494bea20fd555e805b5?context=explore) in one of our products and have few questions related to that.

Is the EOL for the docker image same as the [ubuntu OS](https://ubuntu.com/about/release-cycle) as well?

Is the license for the docker image same as [ubuntu OS](https://ubuntu.com/legal/intellectual-property-policy)?

Is the Ubuntu docker image will be updated during Ubuntu ESM as well?

Is this image free to use for enterprise usage?

Is there any commercial support available for the base docker image usage? If Yes, what are the features available as part of it.

Is there any forums or mailing list for the questions related to the usage of the docker image?

**Comment by valentincanonical** [comment]
Hey @bharanitharanm, thanks for reaching out and apologies for the delay! (the Canonical team is not actively monitoring this repo) I'm Valentin, Product Manager at Canonical for these container images.

Glad to see you selected Ubuntu as a base image in one of your products. Feel free to reach out to me in private if you wish to discuss your use case; I'm always happy to hear these stories and help where I can!

> Is the EOL for the docker image same as the Ubuntu OS as well?

Yes, the EOL is the same for the Ubuntu OS as for the Ubuntu OCI image (https://ubuntu.com/about/release-cycle).

> Is the license for the docker image same as ubuntu OS?

The Licensing is indeed the same. I invite you to refer to https://ubuntu.com/legal, especially about Trademarks usage. In embedding situations, as yours seem to be, we're keen on being involved. There might not be a need for a commercial relationship. Yet, we'd like to understand how our product is being used to improve it! Additionally, in some cases, the nature of the embedding will require a commercial relationship.

> Is the Ubuntu docker image will be updated during Ubuntu ESM as well?

Not the one you're referring to (i.e. the "ubuntu" image from Docker Hub). However, we have a program for our customers to provide updated docker images for the extended security updates timeframe (10 years). The program includes the Ubuntu image as well as runtime and appliance images (https://ubuntu.com/security/docker-images). Let me know if you want more information!

> Is this image free to use for enterprise usage?

Yes.

>  Is there any commercial support available for the base docker image usage? If Yes, what are the features available as part of it.
> Is there any forums or mailing list for the questions related to the usage of the docker image?

Commercial support is indeed available. It includes phone/ticket support for base images in most enterprise use cases (and not only on Ubuntu hosts). Support is an extra feature of the security updates and trusted delivery program I mentioned before.
Sure, please reach out to rocks@canonical.com with your detailed inquiry; we'd be happy to support you! (and even just chat about your use case) 

You can also reach out to me directly on social channels (I mostly use Twitter and LinkedIn),
Thanks again!
Valentin Viennot

(@tianon , I think we can close this issue)
