### ISSUE TITLE
Update Ubuntu Focal 20.04 image to 20220105

### ISSUE THREAD

**Issue by j-chao** [tianon/docker-brew-ubuntu-core#227]
This is a request to update the Ubuntu focal image to the latest version (20220105) found here: 
https://partner-images.canonical.com/core/focal/20220105/
which contains a number of CVE vulnerability fixes for ubuntu.

**Comment by tianon** [comment]
Nice catch, thanks for the prod -- we're just over the month mark too, so we're due either way.

@toabctl @woky @mwhudson I've hit the job to stage this, but wonder if there's any reason we might want to wait? (very near updates I'm not aware of, etc)

**Comment by woky** [comment]
@tianon @j-chao the rootfs linked in the OP is core rootfs, but Docker Hub images are built from these https://partner-images.canonical.com/oci/focal/, where rootfs for focal is stale. I'm currently working on the problem, hopefully it'll build overnight and I'll then ask you in the morning to trigger the build.

**Comment by toabctl** [comment]
@tianon https://partner-images.canonical.com/oci/ is up-to-date now. please trigger the job. TIA

**Comment by toabctl** [comment]
https://github.com/docker-library/official-images/pull/11612 is the update.

**Comment by toabctl** [comment]
@j-chao out of interest - which CVEs will the update fix for focal? I don't see any in the updated packages.

**Comment by j-chao** [comment]
Hi @toabctl,
I was looking for the fix to https://ubuntu.com/security/notices/USN-5201-1 specifically.

**Comment by toabctl** [comment]
> Hi @toabctl, I was looking for the fix to https://ubuntu.com/security/notices/USN-5201-1 specifically. Looking at the manifests now, I'm not sure if this update contains the fix either...but thanks anyways!

The Ubuntu focal docker image does not contain python by default. So the image was not affected by this CVE. If you install (`apt-get install`) python you get the version from the archive which has the fixes.

**Comment by toabctl** [comment]
@tianon this can be closed imo.

**Comment by tianon** [comment]
Oops yep, sorry, I forgot about it. :sweat_smile:
