### ISSUE TITLE
dpkg broken in Jammy image on singular-doc pkg extraction

### ISSUE THREAD

**Issue by dimpase** [tianon/docker-brew-ubuntu-core#230]
Using official Jammy image in Docker (macOS) and Podman (Fedora).
In both cases, using CLI in the image and running
```
apt install singular-doc
dpkg -V singular-doc
```
reports a lot of missing files. In fact, the only present files are dangling links to missing files in the package.
The package itself is not broken - extracting it in Jammy not in Docker/Podman (say, in an `lxc` container) works.
And extracting it in Debian/bookworm CLI  run in Docker works too.

As well, the same behaviour is observed using the corresponding `singular-doc_4.2.1-p3+ds-1_all.deb` file, and installing it using `dpkg -i`. This points to `dpkg` as the culprit.

-------

What's unusual about `singular-doc_4.2.1-p3+ds-1_all.deb` ? I suppose 
* `data.tar` is compressed using `zst`
* it contains symbolic links within the tarball.

The  `data.tar.zst` tarball extracted from `.deb` works fine in Docker image CLI (assuming `zstd` is installed), so I presume it's something to do with `dpkg` expaning the file by itself.

This was found while working on https://trac.sagemath.org/ticket/32789

**Comment by mwhudson** [comment]
docker images contain a dpkg-filter to not install docs by default. You can run 'unminimize' to remove the filter and restore the missing files.
