### ISSUE TITLE
Rerun build job to update ubuntu image LTE 20.04

### ISSUE THREAD

**Issue by j-ferreira** [tianon/docker-brew-ubuntu-core#238]
Hello together, 

there is a new Ubuntu image for 20.04 in https://partner-images.canonical.com/oci/focal/current/ 
These new image has a few CVE fixes for OpenSSL etc.

Can you rerun your build job? 

As a suggestion for improvement: it would also be useful to run the job automatically as soon as a new image exists.

**Comment by tianon** [comment]
This repository is no longer canonical; see https://github.com/tianon/docker-brew-ubuntu-core/pull/248 for more details.
