### ISSUE TITLE
Remove middle steps in image creation

### ISSUE THREAD

**Issue by mkostrikin** [tianon/docker-brew-ubuntu-core#24]
Hello,
 Did a pull request: https://github.com/tianon/docker-brew-ubuntu-core/pull/19
 This makes image creation in one RUN
1. Make image smaller
2. Remove few layers from final image

Thanks,

**Comment by lkwg82** [comment]
outdated?

**Comment by mkostrikin** [comment]
Yes, this was fixed by someone else.
Removed dist-upgrade, but seems fine.
