### ISSUE TITLE
Please provide 32-bit runtime capable containers

### ISSUE THREAD

**Issue by xnox** [tianon/docker-brew-ubuntu-core#28]
Hello, 

As per https://github.com/docker/docker/issues/611 it would be nice if ubuntu containers were provided with 32-bit abi support - that is with dpkg --add-architecture i386 enabled and e.g. libc6:i386 installed. This would enable people to have 32-bit workloads on otherwise 64-bit-only docker hosts/containers.

**Comment by tianon** [comment]
These tarballs are the stock rootfs tarballs provided by Canonical (specifically, https://partner-images.canonical.com/core/), so I'm not actually permitted to do more modification to them than what's already being done here (they're very specific about providing these tarballs built from their own systems for us to call this Ubuntu -- I'm essentially just the proxy maintainer here).

That being said, I've got two points of interest for you.  One is https://hub.docker.com/r/i386/ubuntu/ (for a pure 32bit image).  The other is the following:
```console
$ docker pull ubuntu:precise > /dev/null
$ docker run -it --rm ubuntu:precise dpkg --print-foreign-architectures
i386
$ docker pull ubuntu:trusty > /dev/null
$ docker run -it --rm ubuntu:trusty dpkg --print-foreign-architectures
$ docker pull ubuntu:wily > /dev/null
$ docker run -it --rm ubuntu:wily dpkg --print-foreign-architectures
$ docker pull ubuntu:xenial > /dev/null
$ docker run -it --rm ubuntu:xenial dpkg --print-foreign-architectures
```

So, this definitely _used_ to be standard (as evidenced by precise having it), but is no longer considered to be as such.
