### ISSUE TITLE
Is it normal that image id b7cf8f0d9e82 isn't based on image id 511136ea3c5a (scratch) like the previous ones ?

### ISSUE THREAD

**Issue by gissehel** [tianon/docker-brew-ubuntu-core#30]
Almost all images derivate from image id `511136ea3c5a` (which could be labelled scratch, because it's the one choosen when using `FROM scratch`). At least since some docker version 0.x if I'm not mistaken.

And recently, the ubuntu image `b7cf8f0d9e82` (tags: `ubuntu:14.04` `ubuntu:14.04.2` `ubuntu:latest` `ubuntu:trusty` `ubuntu:trusty-20150320`) didn't derive from "scrach".

Is it a bug in the image creation process ? Or a new direction/convention about root images ?

**Comment by tianon** [comment]
See the updated description on https://registry.hub.docker.com/_/scratch/, especially the second paragraph:

> As of Docker 1.5.0 (specifically, docker/docker#8827), `FROM scratch` is a no-op in the `Dockerfile`, and will not create an extra layer in your image (so a previously 2-layer image will be a 1-layer image instead).

**Comment by gissehel** [comment]
Ok, that address my question !
