### ISSUE TITLE
Update images?

### ISSUE THREAD

**Issue by envygeeks** [tianon/docker-brew-ubuntu-core#33]
It seems that even though you recently added Wily, none of the other images are getting the updates that Ubuntu is providing via the partner site core images.  For example, vivid was recently updated on the 11th and on the 29th and lots of times in-between before and after you created the Wily image... yet Vivid received no update.  Can we please get more standard updates to this image?

**Comment by tianon** [comment]
All the variants of this image were updated very recently; check out the
dist branch for the rootfs tarballs.

**Comment by tianon** [comment]
https://github.com/tianon/docker-brew-ubuntu-core/commit/67accc07b2f77dbf00dc4e2d5b90c00abc225ec6


- `ubuntu:precise`: 20150612
- `ubuntu:trusty`: 20150612
- `ubuntu:utopic`: 20150612
- `ubuntu:vivid`: 20150611
- `ubuntu:wily`: 20150611

**Comment by envygeeks** [comment]
Awesome, thanks!

**Comment by sgoblin** [comment]
Ubuntu vivid now has 20150802, trusty has 20150730, and precise has 20150729

**Comment by envygeeks** [comment]
This issue is largely fixed for us mostly because we started building our own scratch images (not because there is anything wrong with this image) but because we want to make our additions minimal and as base as they could get.
