### ISSUE TITLE
How to install ubuntu software inside this docker?

### ISSUE THREAD

**Issue by yhjhoo** [tianon/docker-brew-ubuntu-core#35]
How to install ubuntu software inside this docker?

I tried this 
$ docker run ubuntu:14.04 apt-get install openjdk-jre

It prompted error msg denpenancy is not going to installed.

**Comment by ghanan** [comment]
Inside the container, apt-get does't connect and the commands host, nslookup, ping, telnet, ssh are not installed.
networkclt reports IP an gateway en eth0
¿How can I troubleshoot it?

**Comment by smiller171** [comment]
@yhjhoo if you were going to do it that way you would need a -y, but the better way would be to create a simple Dockerfile and use `docker build .`

```Dockerfile
FROM: ubuntu:14.04
MAINTAINER: yhjhoo
RUN apt-get install openjdk-jre -yq && apt-get clean
```

**Comment by lkwg82** [comment]
is that solved?

**Comment by OWSM** [comment]
@lkwg82 I'm pretty certain this is user error.

**Comment by tianon** [comment]
This is definitely user error -- to be able to `apt-get install`, you must `apt-get update` first to update list files:
```dockerfile
FROM ubuntu:14.04
RUN apt-get update && apt-get install -y openjdk-jre
```

Additionally, any issues `apt-get` has with communicating externally are going to be host or Docker issues, not specific to this image. :+1:
