### ISSUE TITLE
Trusty cloud image has invalid Python installations

### ISSUE THREAD

**Issue by mikedoug** [tianon/docker-brew-ubuntu-core#38]
https://github.com/tianon/docker-brew-ubuntu-core/commit/e9338b6f9ec01801bd5cc75743efe04949d123cf#diff-853f229e404c9525584cef7936eeafadR110

The manifest shows that there are parts of Python 3.4.0 and parts of Python 3.4.3 installed.  Further, when you attempt to `apt-get install -y python3-dev` it blows up miserably because of these 3.4.3 bits that are installed where python3-dev expects to install 3.4.0 instead.

Canonical doesn't even show Python 3.4.3 to be available for Trusty.  How are these packages getting installed?

**Comment by tianon** [comment]
@OddBloke any ideas how we're getting this oddity with the latest builds?

https://github.com/docker-library/official-images/issues/1110 is more on the same problem :confused:

**Comment by mikedoug** [comment]
Yes, I've done a bit more research.

So here's the problem.  The Dockerfile is using the root file system provided by https://partner-images.canonical.com/core/trusty/.  The 20150925 and 20151001 builds of the Ubuntu 14.04 (Trusty) cloud image have a fubared Python installation with a mix of Python 3.4.3 and Python 3.4.0.  (You can see that in the manifest, look for the `python` lines: https://partner-images.canonical.com/core/trusty/20150925/ubuntu-trusty-core-cloudimg-arm64.manifest)

On 2015-10-07 (two days ago), the maintainers of the Ubuntu Docker image updated their root file system with the 20151001 build from Canonical.  This broke the Python 3 installation such that you could no longer install the python dev packages because of mismatched versions.

Canonical has provided a new build today (20151009) where they have reverted to a pure Python 3.4.0 installation (no more mismatch!).  Once they update the Docker image to use this cloud image root file system, then all will be well with the ubuntu:14.04 Docker image.  Until then, hard code your docker base image to ubuntu:trusty-20150814 if you want a working Python 3 installation.

**Comment by mikedoug** [comment]
It'd also be nice if someone with some weight could contact Canonical and find out what the heck is going on. This isn't the first time Python 3.4.3 has leaked into the cloud images and has caused us no end of problems when it flopped back.

**Comment by tianon** [comment]
The upstream bug is https://bugs.launchpad.net/bugs/1505164 -- images are rebuilt, and PR is open at https://github.com/docker-library/official-images/pull/1114.
