### ISSUE TITLE
$LD_LIBRARY_PATH not set

### ISSUE THREAD

**Issue by cweagans** [tianon/docker-brew-ubuntu-core#39]
Steps to reproduce:

1) Compile openconnect in the 15.04 container
2) Run openconnect  and get this error:
```
openconnect: error while loading shared libraries: libopenconnect.so.5: cannot open shared object file: No such file or directory
```

To fix, I added this to my Dockerfile:

```
ENV LD_LIBRARY_PATH /usr/local/lib:/usr/lib:/lib
```

Is there any reason not to make this the default?

**Comment by tianon** [comment]
Hmm, did you try adding `RUN ldconfig` to your `Dockerfile` after openconnect is compiled to force the `.so` cache to be refreshed?

**Comment by tianon** [comment]
(See `python` for an example of this, which also compiles into `/usr/local`: https://github.com/docker-library/python/blob/2f33ab315894baa2d881e2a72ab298a5b67c2687/3.5/Dockerfile#L32)

**Comment by cweagans** [comment]
I didn't try that, no. I'll give it a go in a few days (pretty busy with other things atm).

**Comment by tianon** [comment]
Sounds good (and no rush)! :+1:

**Comment by tianon** [comment]
Closing, but feel free to open a new issue with more details if you can reproduce! :+1:
