### ISSUE TITLE
New vulnerable packages since last refresh for ubuntu:latest

### ISSUE THREAD

**Issue by shamiq** [tianon/docker-brew-ubuntu-core#40]
Heyo, did some verifications against ubuntu:latest 
```
$ docker pull ubuntu
Using default tag: latest
latest: Pulling from library/ubuntu
Digest: sha256:b53bb7b0d18842214ac7472c2a8801e8682c247d30f1ba4bab0083a2e2e091ea
Status: Image is up to date for ubuntu:latest
```
and found the following packages were out of date in the base:
>isc-dhcp-client 4.2.4-7ubuntu12.3
isc-dhcp-common 4.2.4-7ubuntu12.3
libgnutls-openssl27 2.12.23-12ubuntu2.3
libgnutls26 2.12.23-12ubuntu2.3
libpng12-0 1.2.50-1ubuntu2.14.04.1

Can we refresh? Thanks!

**Comment by tianon** [comment]
Updated image is being pushed as we speak, thanks.

**Comment by shamiq** [comment]
:thumbsup: Thanks for patching! Did you get my email at your Debian address? :thumbsup:

**Comment by tianon** [comment]
Yes, although I'd much rather discuss those types of things here in the
open.

I'm appreciative of a poke when there are serious/notable issues to fix or
updates to apply, but I do already have a plethora of systems (both
automated and human-driven) whose notifications I readily have trouble
processing in a timely or useful manner, so I would really rather not add
even more into my own workflow.

**Comment by shamiq** [comment]
Perfectly fine with me. I can get a bot that pushes issues here directly, if that's cool. Is there a good way for me to know when the new image is pushed?

**Comment by tianon** [comment]
Not for when the image is pushed to the Hub directly, but it usually
builds/pushes soon after the PR over on the official-images repository
merges (https://github.com/docker-library/official-images/pull/1357 being
an example for the most recent push).

**Comment by shamiq** [comment]
Hm, that's not perfect, but I'll try to make it work. I'll be filing based on CVEs that the ubuntu team fixes for packages in this based image.

**Comment by tianon** [comment]
Your best bet for creating issues that are actually relevant to this repo
(and the contents of it) is probably to run your tests directly on the
rootfs tarballs in the "dist" branch of this repo.
