### ISSUE TITLE
Tab Completion

### ISSUE THREAD

**Issue by svalleru** [tianon/docker-brew-ubuntu-core#42]
How can I enable tab completion ? I tried installing bash-completion using apt, but, it didn't work.

**Comment by tianon** [comment]
Once it's installed, you have to restart your shell session (or start a new one).  Your best bet is likely going to be to write a simple `Dockerfile` which installs it, and then use _that_ instead of `debian:...` directly (if you need this on the base image itself).

**Comment by tianon** [comment]
Alternatively, I _think_ there's some file it installs that can be `source`d from the current session, but I don't recall the exact details offhand.

**Comment by svalleru** [comment]
Adding `RUN apt-get install -y bash-completion` to `Dockerfile` did the trick. 
Would love to see the tab-completion enabled by default in the base image, though.

**Comment by tianon** [comment]
The base image is kept intentionally slim -- we use `--variant=minbase` on our invocation of `debootstrap` so that we have the smallest possible set of packages that we can still call "Debian".
