### ISSUE TITLE
SSH contection

### ISSUE THREAD

**Issue by theodormachnich** [tianon/docker-brew-ubuntu-core#43]
Hi,
thank you for this 14.04.04 Image from Ubuntu.
A short Question I am new and I try to connect by ssh to the running Server but the connection is always refused.
What can I do?
Or what I doing in the wrong way?
Also other synology users told me there having the same difficulties.
I run the Image on my synology Diskstaion.
I got this Errors:

ssh -p 65535 root@192.168.1.118

ssh -p 65535 root@192.168.1.118 -v
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to 192.168.1.118 [192.168.1.118] port 65535.
debug1: Connection established.
debug1: identity file /home/dufoy/.ssh/id_rsa type -1
debug1: identity file /home/dufoy/.ssh/id_rsa-cert type -1
debug1: identity file /home/dufoy/.ssh/id_dsa type -1
debug1: identity file /home/dufoy/.ssh/id_dsa-cert type -1
debug1: identity file /home/dufoy/.ssh/id_ecdsa type -1
debug1: identity file /home/dufoy/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/dufoy/.ssh/id_ed25519 type -1
debug1: identity file /home/dufoy/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.6
ssh_exchange_identification: read: Connection reset by peer

Best Theo

**Comment by tianon** [comment]
Have you done anything to prepare the `sshd_config` of the image prior to running? (for example, I think the default value of `PermitRootLogin` is non-`yes`, and you'll need to be setting a password for root)

**Comment by AnonJedi** [comment]
I have same problem. Create **sshd_config** and add _PermitRootLogin_ and _UsePAM_ rules. Now i have next message:

`OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to localhost [127.0.0.1] port 222.
debug1: Connection established.
debug1: identity file /home/vik/.ssh/id_rsa type 1
debug1: identity file /home/vik/.ssh/id_rsa-cert type -1
debug1: identity file /home/vik/.ssh/id_dsa type -1
debug1: identity file /home/vik/.ssh/id_dsa-cert type -1
debug1: identity file /home/vik/.ssh/id_ecdsa type -1
debug1: identity file /home/vik/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/vik/.ssh/id_ed25519 type -1
debug1: identity file /home/vik/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
ssh_exchange_identification: Connection closed by remote host`

**Comment by tianon** [comment]
Closing since this is really old, and it appears what you're really after is a VM. :smile: :heart:
