### ISSUE TITLE
16.04 is still dev branch not release branch?

### ISSUE THREAD

**Issue by learningpro** [tianon/docker-brew-ubuntu-core#46]
I build a new container using "FROM ubuntu16.04"and found that it was dev branch 
```bash
 cat /etc/issue
Ubuntu Xenial Xerus (development branch) \n \l
```

**Comment by ailispaw** [comment]
Not merged yet on upstream.
https://github.com/docker-library/official-images/pull/1657

**Comment by graingert** [comment]
@learningpro done now!

**Comment by tianon** [comment]
Indeed, images are up now.
