### ISSUE TITLE
Yakkety yakkety yakkety yakkety yakkety yakkety yakkety yakkety yak

### ISSUE THREAD

**Issue by graingert** [tianon/docker-brew-ubuntu-core#47]
Time for yakkety to be tagged?

**Comment by tianon** [comment]
As soon as they're available from https://partner-images.canonical.com/core/, I can add them here.

**Comment by kees-jan** [comment]
It seems they are available now :-) :pray:

**Comment by tianon** [comment]
Indeed, but only partially -- the folder is missing the "current" symlink, and both the `*SUMS` files and their signatures.  As I understand it, Canonical is working on figuring out what's wrong with the builds, and they're planning to let me know when they're ready to consume.  I'll give them another friendly prod just to make sure it's still on their radar. :+1:

**Comment by kees-jan** [comment]
In possibly related news, the yakkety image that is currently available seems to be lacking the build-essentials package. build-essentials appears to be present in all older ubuntu docker images.

**Comment by alxempirical** [comment]
Also, the [yakkety image from May 25](https://partner-images.canonical.com/core/yakkety/20160525/) has some sort of authentication issue which prevents you from changing passwords.  Definitely not ready for prime time.

```
root@81ec52b25c2f:/# passwd
passwd: Authentication token manipulation error
passwd: password unchanged
```

**Comment by kees-jan** [comment]
I wouldn't care much about that. I'd use the image primarily as a build environment. Yakkety won't improve if one can't build software for it :wink:
