### ISSUE TITLE
xenial leaves in a broken systemd

### ISSUE THREAD

**Issue by twk3** [tianon/docker-brew-ubuntu-core#54]
The Xenial image stubs out initctl but leaves a broken systemd in place.

```
root@4c9e0817c0fe:/# systemctl
Failed to connect to bus: No such file or directory
root@4c9e0817c0fe:/# init
Couldn't find an alternative telinit implementation to spawn.
```

**Comment by tianon** [comment]
It's not broken so much as not running at all (hence why `systemctl` cannot talk to it).  The systemd package should be functional, if you can manage to get systemd itself running.

The most successful attempts I've seen at doing so involve stubbing out services that systemd expects to initialize (esp. hardware-related services) which aren't necessary within containers, such as is done in http://developers.redhat.com/blog/2014/05/05/running-systemd-within-docker-container/, and adding additional capabilities at runtime, but it's definitely not for the faint of heart (in my experience).
