### ISSUE TITLE
Apt::AutoRemove::SuggestsImportant 'false'

### ISSUE THREAD

**Issue by dnwe** [tianon/docker-brew-ubuntu-core#57]
Has this just been overlooked when using the debootstrap tweaks from [contrib/mkimage/debootstrap#L132-L150](https://github.com/docker/docker/blob/084c72e/contrib/mkimage/debootstrap#L132-L150), or was it intentionally omitted due to the resulting change in behaviour in downstream images?

**Comment by tianon** [comment]
Heh, that's an indicator of how long it's been since we resynced our tweaks with those from the script -- https://github.com/docker/docker/pull/11124 is the Docker PR which added that (Mar 2, 2015), and we just haven't pulled in the change yet. :smile:

**Comment by dnwe** [comment]
Cool. I was hoping that was the case as it'd be great to see this merged in as it would tidyup a lot of our Dockerfiles that had been doing explicit naming of dependencies of other build dependencies - which makes them somewhat brittle

**Comment by tianon** [comment]
This fix will probably go out either Monday or Tuesday of next week. :+1:

(infra folks get understandably irritated when we push `ubuntu` on Friday or close to EOD :innocent:)
