### ISSUE TITLE
login as: ????? password: ?????

### ISSUE THREAD

**Issue by dtrimsd** [tianon/docker-brew-ubuntu-core#58]
I'm running under WIndows 10.

I can create the container. I found out the correct IP address to reference. I can use PuTTY to access the instance. But then I'm asked two simple questions login as: ???? password: ????

No matter what I enter I receive an Access denied. 

What are the default userid/password or what are the rules/process to establish them?

Thanks

**Comment by dtrimsd** [comment]
sigh... never mind

**Comment by tianon** [comment]
Not sure what you're asking about -- your Docker VM?  Trying to SSH into a container doesn't exactly make sense unless you're running `sshd` in the container.  If you need to run debugging tools (such as a shell) on an existing container, I'd recommend using `docker exec`.

If you're asking about passwords in the image, however, I don't actually know them.  Canonical generates the tarballs, but it is my understanding that all passwords are disabled by default (`root`'s password certainly is).  The `chpasswd` utility should be a reasonably straightforward way to change that via a `Dockerfile` if it's necessary for one of the users to have a password, however (something like `RUN echo 'root:docker.io' | chpasswd` to set `root`'s password to `docker.io`).

**Comment by dtrimsd** [comment]
Trying to SSH into a container is exactly what I was trying to do. I was
hoping I could use a Docker container to run a low resource instance of
Ubuntu and use it a way I'm using a digitalocean.com cloud server to learn
a bit of Linux and node.js. To my Microsoft WIndows view of the world, it
looked like something worth trying.

Thank you for the response.
