### ISSUE TITLE
16.04.1 not available?

### ISSUE THREAD

**Issue by aklaing** [tianon/docker-brew-ubuntu-core#60]
Would like a docker image for 16.04.1 please.
Thanks

**Comment by zsalzbank** [comment]
It was posted two days ago: https://partner-images.canonical.com/core/xenial/20160809/

For now you can do it manually by changing `xenial/alias` to `16.04.1` and running `./update.sh xenial`.

**Comment by aklaing** [comment]
Thank you very much!
-Ambrose

On Thu, Aug 11, 2016 at 10:43 AM, Zachary Salzbank <notifications@github.com

**Comment by yosifkit** [comment]
It is on the hub now: `ubuntu:xenial-20160809`. :smile:
