### ISSUE TITLE
GUI application in docker failed to connect Mir

### ISSUE THREAD

**Issue by jacknlliu** [tianon/docker-brew-ubuntu-core#68]
I tested the  docker image `ubuntu:16.04` on Fedora host system which not use the Mir display server, and I got the following error when I run a gui application:

```
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
```

Could I run ubuntu docker image on other Linux distribution with other display server?

**Comment by tianon** [comment]
I don't know much about how Mir works, but this is expected -- you're not running Mir inside the container (or outside, for that matter, as you pointed out).  We have the same problem when attempting to run X applications within a Docker container, and the solution there is usually to bind-mount the X socket -- see https://blog.jessfraz.com/post/docker-containers-on-the-desktop/ for a good article on that subject. :+1:
