### ISSUE TITLE
fstrim included and has default /etc/cron.weekly entry

### ISSUE THREAD

**Issue by codywohlers** [tianon/docker-brew-ubuntu-core#72]
From what I understand you don't need to run `fstrim` in a container.  But if you install `cron` it will pick up the default `/etc/cron.weekly/fstrim` entry and run every week and produce the following errors:
```
$ docker run -ti -v tmp:/tmp2 ubuntu:16.04 /sbin/fstrim --all
fstrim: /etc/hosts: not a directory
fstrim: /etc/hostname: not a directory
fstrim: /etc/resolv.conf: not a directory
fstrim: /tmp2: FITRIM ioctl failed: Operation not permitted
```
I think the `/etc/cron.weekly/fstrim` entry should be removed from the image so that if you install cron it is not run.  Also, should `/sbin/fstrim` even be included at all?

reference: http://serverfault.com/questions/820169/should-i-be-running-fstrim-in-a-container/

**Comment by tianon** [comment]
The contents of this image's rootfs are controlled by Canonical's official build process, so I think the best place to discuss this would be in an issue over at https://bugs.launchpad.net/cloud-images :+1:

**Comment by codywohlers** [comment]
I was considering filing a bug with Canonical but i think one might want `fstrim` in a VM?  (If the same image is used for services like AWS as well as Docker images) If that's the case then would Canonical make a different version for docker or should we make mods here?  (I'm not sure of the build process)  The answer depends on where to start the discussion about `fstrim` (here or on launchpad)

(sorry the delay in replying, didn't have notifications on)

**Comment by tianon** [comment]
I _think_ the tarballs we consume are Docker-only (or at least containers-only), but even still, IMO adding `fstrim` at a higher level during image building would be sane in those cases.  I'm not anything resembling a decider on that though, so the folks at Canonical who make that call might disagree. :smile:

**Comment by codywohlers** [comment]
Filed a bug at https://bugs.launchpad.net/cloud-images/+bug/1652622  I think it is definitely an upstream issue.  Workaround for now is to add `RUN rm /etc/cron.weekly/fstrim` to my Dockerfile.
