### ISSUE TITLE
Packages installed in base images

### ISSUE THREAD

**Issue by Kiemes** [tianon/docker-brew-ubuntu-core#73]
I wonder how the list of base packages is determined?
In [trusty](https://github.com/tianon/docker-brew-ubuntu-core/blob/9c78896fe39d5be95cc4a6ae6c0475599a1bc396/trusty/ubuntu-trusty-core-cloudimg-amd64.manifest#L180-L181), we see for example `vim` and `less`, which we do not see in [xenial](https://github.com/tianon/docker-brew-ubuntu-core/blob/9c78896fe39d5be95cc4a6ae6c0475599a1bc396/xenial/ubuntu-xenial-core-cloudimg-amd64.manifest).

Any specific reason for that?

**Comment by tianon** [comment]
The list of packages included is determined by Canonical -- we simply consume the tarballs they provide.

I know it _used_ to be based on [the `ubuntu-minimal` package](http://packages.ubuntu.com/trusty/ubuntu-minimal), but I don't know whether it still is, or whether it's more custom now to get a smaller base set specifically for the purposes of Docker.

https://partner-images.canonical.com/core/ is where our tarballs are hosted, and https://launchpad.net/cloud-images / https://bugs.launchpad.net/cloud-images is the team responsible for building them. :+1:

**Comment by Kiemes** [comment]
@tianon thanks for the info.
@codywohlers why did you thumb up? Did you want to say that it still is based on the ubuntu minimal package? Or did you want to say that they are building a Docker specific image?

**Comment by codywohlers** [comment]
@Kiemes oh no particular reason other than I agree with tianon and he responded politely with technical references.  Maybe I'm being too social-networky on here... :)  

I'm not sure of the history of `ubuntu-minimal` but while exploring an fstrim issue I can also confirm that the `partner-images` tarball is used to make the ubuntu docker image and the `cloud-images` launchpad project is the place to report bugs and discuss things.

Cheers!

**Comment by tianon** [comment]
Closing, given that the original question is now answered. :+1:
