### ISSUE TITLE
Service management not working in 14.04

### ISSUE THREAD

**Issue by dploeger** [tianon/docker-brew-ubuntu-core#74]
In the 14.04 repo, all commands for service management (like /sbin/start, /sbin/stop or /sbin/status) return 0, even for non-existing services:

```bash
root@9f854b345934:~# ls /etc/init/*foo*
ls: cannot access /etc/init/*foo*: No such file or directory
root@9f854b345934:~# status foobar
root@9f854b345934:~# echo $?
0
root@9f854b345934:~# start foobar
root@9f854b345934:~# echo $?
0
```

Existing services aren't managed either.

**Comment by dploeger** [comment]
Argh. It may be, because the docker container was set up using kitchen's docker driver, which has a "disable_upstart" parameter. m(

I'm testing that and will close this issue, if it works.

**Comment by tianon** [comment]
The issue is that your container isn't running `upstart` at all, which is what these commands communicate with (and really probably shouldn't be -- running upstart in a container is pretty fragile in my experience).
