### ISSUE TITLE
ldconfig and new installed .so's in docker

### ISSUE THREAD

**Issue by rollinroy** [tianon/docker-brew-ubuntu-core#77]
Hi.  I'm creating a new image using docker commit based on docker hub ubuntu:16.04 image as follows:
1. ) executing docker run -it ubuntu:16.04 /bin/bash 
2.) from the shell installing various software includiung Intel's MKL, R, openmpi, etc 
3.) creating a config file in /etc/ld.so.conf.d supplying the paths for the shared libraries that are installed in "non-standard" locations
3.) executing docker commit <the container> <some tag> to create a new image
(Because installing the various software is fairly complex requiring the installation many associated packages and extensive makefiles, it's not very practical to use a docker file).  

When I run the newly created image (with the /bin/bash command), all the software appears to be correctly installed except some of the newly installed shared libraries cannot be found (executing "ldconfig -p" command). But when I execute "ldconfig", it looks like the module in /etc/ld.so.conf.d/ is read and the shared libraries are correctly identified.

I could create another new image using a docker file which just executes the "ldconfig" command and I suspect all the shared libraries will be found.  Is there some way besides using a docker file to insure that ldconfig files are executed as part of the new ubuntu image?  tia.

cheers, roy

**Comment by tianon** [comment]
This is more of a generic Ubuntu question, but I'll do my best to answer it.

I think you'll probably want to execute `ldconfig` before you run your `docker commit`:

> ldconfig is a program that is used to maintain the shared library cache. This cache is typically stored in the file /etc/ld.so.cache and is used by the system to map a shared library name to the location of the corresponding shared library file.

(Otherwise, you'll _have_ to re-generate the cache every time you start a new container, but you want that cache updated in your Docker image.) :+1:
