### ISSUE TITLE
Locale instructions in Readme

### ISSUE THREAD

**Issue by mgwidmann** [tianon/docker-brew-ubuntu-core#78]
I had to add this to get applications properly recognizing the right locale:

```
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
RUN locale-gen en_US en_US.UTF-8
RUN dpkg-reconfigure locales
```

It would be nice to have this information in the README so that it can be easily found. I did not get my application to work correctly without *both* the `ENV`s and the `RUN`s... I am using the `ubuntu:16.04` image.

**Comment by tianon** [comment]
I would recommend trying "ENV LANG C.UTF-8" -- I've found that to be
sufficient for almost all my locale-related needs inside containers, and
it's included in both Ubuntu and Debian by default.

**Comment by mgwidmann** [comment]
That works... It would be helpful if that information was available on the readme here https://hub.docker.com/_/ubuntu/

**Comment by tianon** [comment]
Good point!  Filed https://github.com/docker-library/docs/pull/861 to add a note (which I've copied from Debian, which already noted this :smile:). :+1:
