### ISSUE TITLE
softlink /etc/localtime is invalid; points to missing file

### ISSUE THREAD

**Issue by sfrolich** [tianon/docker-brew-ubuntu-core#81]
Just got your update an hour ago and see this softlink

lrwxrwxrwx. 1 root root 27 Apr 10 18:11 /etc/localtime -> /usr/share/zoneinfo/Etc/UTC

The  /usr/share/zoneinfo/ directory does not exist in your latest image.

**Comment by yosifkit** [comment]
That comes from the `tzdata` package. If this new version is causing issues for your application, you can just install `tzdata`.

The list of packages included is determined by Canonical -- we simply consume the tarballs they provide.

https://partner-images.canonical.com/core/ is where our tarballs are hosted, and https://launchpad.net/cloud-images / https://bugs.launchpad.net/cloud-images is the team responsible for building them. :+1:

**Comment by sfrolich** [comment]
Ok that's fine. Just for my sanity tzdata or the files that were in tzdata were in the container image prior to today's release?

**Comment by tianon** [comment]
Expanding the diff in https://github.com/docker-library/official-images/pull/2852#issuecomment-293697246, it would appear so. :+1:

**Comment by sfrolich** [comment]
adding tzdata fixed my problem. Closing issue. Thanks!
