### ISSUE TITLE
ubuntu 14.04 fails to run apt-get update (https error)

### ISSUE THREAD

**Issue by cdeterman** [tianon/docker-brew-ubuntu-core#89]
I pulled a fresh image of ubuntu:14.04 on my Windows machine.

    docker run -it ubuntu:14.04

This downloads fine and opens the session.  However I cannot run `apt-get update` with the following error:

   >E: The method driver /usr/lib/apt/methods/https could not be found.
   >N: Is the package apt-transport-https installed?

I tried installed apt-transport-https but I only get an error saying:

>Reading package lists... Done
>Building dependency tree
>Reading state information... Done
>E: Unable to locate package apt-transport-https

**Comment by cdeterman** [comment]
@tianon hmm... is that using the docker-toolbox as well?  I failed to mention I am using a Windows 7 machine.

**Comment by tianon** [comment]
Are you on a firewalled network of some kind? (corporate and/or collegiate?)  They sometimes do redirections for non-https traffic or for a captive portal, which could cause issues like this one.

Glad it's working for you now!

**Comment by cdeterman** [comment]
I'm curious though, why isn't `apt-transport-https` in the base image when so much more is using https?

**Comment by tianon** [comment]
Because the default install doesn't require it, and once it's installed it cannot be removed.  In this specific case, the set of packages included in the base image is controlled by Canonical (they build the tarballs directly). :+1:

**Comment by cdeterman** [comment]
Fair enough, thanks for the clarification
