### ISSUE TITLE
docker 32bit?

### ISSUE THREAD

**Issue by R00T88** [tianon/docker-brew-ubuntu-core#93]
is it possibile to have a docker in 32bit modE?

**Comment by yosifkit** [comment]
We do have 32-bit (i386) images: https://hub.docker.com/r/i386/ubuntu/ (which is built from the [dist-i386 branch](https://github.com/tianon/docker-brew-ubuntu-core/tree/dist-i386))

Found via the [other arches](https://github.com/docker-library/official-images/tree/ed3fb22b631098226528ee7a73350e53cb6dc6fd#architectures-other-than-amd64) description in official images.
