### ISSUE TITLE
ppc64le trusty have invalid / wrong apt sources

### ISSUE THREAD

**Issue by xnox** [tianon/docker-brew-ubuntu-core#96]
In ubuntu, we have two mirror networks `archive` and `ports`.
In general, all architectures are shipped on `ports`.
There are `special` architectures that are on the `archive` mirror network - amd64 i386.
The `archive` mirror network has `archive.ubuntu.com` and `security.ubuntu.com` hostname.
The `ports` mirror network carries everything for a given architecture.

Over at https://github.com/xemul/criu/issues/376, we have noticed that ppc64le/ubuntu:trusty images have incorrect sources.list and list `security.ubuntu.com` instead of `ports.ubuntu.com` for the `trusty-security` suite.

How are `sources.list` generated for the `ppc64el/ubuntu:trusty`? And is there something to fix to correct the generated sources in either distribution (e.g. `apt-setup security_host debconf` keys) and/or in the build-scripts?

**Comment by xnox** [comment]
This is not security critical, as all upload into `$adjective-security` are copied and published in `$adjective-updates` as well. Hence this is mostly cosmetic that running `apt-get update` has not found errors.

**Comment by tianon** [comment]
Indeed, see https://bugs.launchpad.net/bugs/1711735, which is tracking this same issue upstream. :+1: (the `sources.list` contents are generated by Canonical in the tarballs they generated for Docker consumption at https://partner-images.canonical.com/core/)

**Comment by xnox** [comment]
Ah thanks
