### ISSUE TITLE
Zesty 20170913

### ISSUE THREAD

**Issue by graingert** [tianon/docker-brew-ubuntu-core#98]
Can you upload zesty 20170913 please?

**Comment by tianon** [comment]
Yeah, it's been a bit since we had an update -- I've kicked on off now. :+1:

**Comment by graingert** [comment]
Great! Thank you very much. Can you ping me when it's done?

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/3448 (once that merges, the images will be built/pushed).
